# Generated by Django 4.1.7 on 2023-04-06 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cowshare', '0003_subcategory_product_sharing_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'category', 'verbose_name_plural': 'Categories'},
        ),
    ]
